server:
  port: 8001
spring:
  application:
    name: sop-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/kerry-sop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SopHikariCP
      maximum-pool-size: 50
  redis:
    host: localhost
    port: 6379
    password: 12345
    database: 9


mybatis-plus:
  global-config:
    # 去掉mybatis-plus logo输出
    banner: false
  type-aliases-package: com.hysz.sop.entity
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

